services:
  - type: web
    name: scorephantom
    env: node
    buildCommand: npm install && cd client && rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: LIVESCORE_API_KEY
        sync: false
      - key: LIVESCORE_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_ENCRYPTION_KEY
        sync: false
      - key: FLUTTERWAVE_WEBHOOK_HASH
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
