import { safeNum } from '../utils/math.js';
import { computeRiskLevel, computeEdgeLabel } from './selectBestPick.js';
function annotate(pick, fv, script) { if (!pick) return pick; const riskLevel = computeRiskLevel(pick, fv, script); const edgeLabel = computeEdgeLabel(pick, riskLevel); return { ...pick, riskLevel, edgeLabel }; }
const MODE_THRESHOLDS = { safe: { minProb: 0.65, gapOdds: 0.018, gapNoOdds: 0.012, allowFallback: false }, balanced: { minProb: 0.58, gapOdds: 0.012, gapNoOdds: 0.008, allowFallback: true }, aggressive: { minProb: 0.52, gapOdds: 0.007, gapNoOdds: 0.004, allowFallback: true } };
export function selectBestPickOrAbstain(rankedCandidates, scriptOutput, featureVector, options = {}) {
  const ranked = rankedCandidates || []; const fv = featureVector || {}; const script = scriptOutput || {}; const mode = options.mode ?? 'balanced'; const thresholds = MODE_THRESHOLDS[mode] ?? MODE_THRESHOLDS.balanced;
  const abstain = (reason, code) => { console.log('[selectBestPickOrAbstain] ABSTAIN [' + mode + '] ' + code + ': ' + reason); return { bestPick: null, backupPicks: ranked.slice(0, 2).map(p => annotate(p, fv, script)), noSafePick: true, noSafePickReason: reason, abstainCode: code, layer2OverrideApplied: false }; };
  if (ranked.length === 0) return abstain('No candidates survived pruning', 'NO_CANDIDATES');
  const top = ranked[0]; const topProb = safeNum(top.modelProbability, 0); if (topProb < thresholds.minProb) return abstain('Best pick prob ' + (topProb*100).toFixed(1) + '% below ' + mode + ' floor (' + (thresholds.minProb*100).toFixed(0) + '%)', 'LOW_PROBABILITY');
  if (ranked.length >= 2) { const hasOdds = ranked.some(c => c.edge != null && c.edge !== 0); const minGap = hasOdds ? thresholds.gapOdds : thresholds.gapNoOdds; const gap = safeNum(top.finalScore, 0) - safeNum(ranked[1].finalScore, 0); if (gap < minGap) { if (options.layer2Override) { console.log('[selectBestPickOrAbstain] L2 override rescued close call gap=' + gap.toFixed(4) + ' mode=' + mode); return { bestPick: annotate(top, fv, script), backupPicks: ranked.slice(1,3).map(p=>annotate(p,fv,script)), noSafePick: false, noSafePickReason: null, layer2OverrideApplied: true, abstainCode: null }; } if (thresholds.allowFallback) { console.log('[selectBestPickOrAbstain] BEST_AVAILABLE fallback [' + mode + '] gap=' + gap.toFixed(4) + ' pick=' + top.marketKey); const annotatedTop = annotate(top, fv, script); return { bestPick: { ...annotatedTop, edgeLabel: 'BEST AVAILABLE', isBestAvailable: true }, backupPicks: ranked.slice(1,3).map(p=>annotate(p,fv,script)), noSafePick: false, noSafePickReason: null, layer2OverrideApplied: false, abstainCode: null }; } return abstain('Top two markets too close (gap=' + gap.toFixed(3) + ', need ' + minGap + ')', 'WEAK_SEPARATION'); } }
  const annotatedTop = annotate(top, fv, script); if (mode === 'safe' && annotatedTop.edgeLabel === 'NO EDGE') return abstain('Best pick has NO EDGE [safe mode rejects this]', 'NO_EDGE');
  const shiftInfo = options.layer2ShiftPp ? ' (L2 shift +' + (options.layer2ShiftPp*100).toFixed(1) + 'pp on ' + (options.layer2ShiftMarket||'?') + ')' : ''; console.log('[selectBestPickOrAbstain] SELECTED [' + mode + '] ' + top.marketKey + ' prob=' + (topProb*100).toFixed(1) + '%' + shiftInfo); return { bestPick: annotatedTop, backupPicks: ranked.slice(1, 3).map(p => annotate(p, fv, script)), noSafePick: false, noSafePickReason: null, layer2OverrideApplied: false, abstainCode: null }; }
