/** leagueTiers.js - League quality tier system. Tier 1: always | Tier 2: stricter | Tier 3: blocked */
const TIER_1 = ['premier league','laliga','la liga','serie a','bundesliga','ligue 1','championship','eredivisie','primeira liga','belgian pro league','jupiler','scottish premiership','scottish premier','champions league','europa league','conference league','major league soccer','mls','copa libertadores','copa sudamericana','brasileirao','saudi pro league','saudi professional league'];
const TIER_2 = ['super lig','ekstraklasa','allsvenskan','eliteserien','veikkausliiga','super league','segunda division','serie b','2nd bundesliga','2. bundesliga','liga i','premier division','premijer liga','prva liga','1. hnl','liga professional','primera a','liga pro','liga mx','j. league','j1 league','k-league 1','indian super league','a-league','uae pro league','qatar stars league','premier soccer league','superettan','superliga','ligat haal','nb i','afc champions league','copa do brasil','copa argentina','copa del rey','fa cup','carabao cup','dfb pokal','coupe de france','coppa italia','league one','league two','league 1','league 2','primera nacional','liga nacional','npfl','primera division','first division a','first division b','liga nacional de futbol profesional','primera liga','liga de futbol profesional'];

const BLOCK_KEYWORDS = ['friendl','reserve','youth','u21','u-21','under 21','u23','u-23','under 23','u19','u-19','under 19','u18','u-18','under 18'];
const TIER_3_EXACT = ['club teams friendlies','national teams friendlies','international friendlies','serie c','serie d','national league north','national league south','national league north / south','segunda b','primera b metropolitana','primera b','primera c','copa do nordeste','3rd league','3rd liga','2nd lig','1st lig','us open cup','national football league 2','national league','elite one','elite two','virsliga','meistriliiga','esiliiga','a lyga','urvalsdeild','ykkonen','ykkosliiga','go-jek liga','pfl','k3 league','k-league 2','v-league','gamma ethniki','tweede divisie','eerste divisie','segunda liga','persha liga','vtora liga','erovnuli liga','garibola','ofc pro league','sg. premier league','tt premier league','ligue i','ligue ii','national 1','championnat national','2nd snl','birindi dasta','1a divisio','regionalliga','western australia','queensland npl','victorian','new south wales','first amateur division','division di honor','leumit league','second professional league','russian cup','usl championship','usl league one','botola','srpska liga','efl trophy','welsh cup','division one','1. division','1st division','1st league','division 1','2nd division','2nd league','3rd league','1 division','national division','football national league','professional league','first league','first professional league','challenge league','usl','king','cypriot','confederations','campionato','2nd liga','nb ii','1. liga promotion','1. liga',,'super league 2','liga pro serie b','primera division b','afc cup','ligue i','division profesional','i-league','primera division'];
// Add primera division to tier 2 explicitly
export function getLeagueTier(tournamentName) { if (!tournamentName) return 3; const name = tournamentName.toLowerCase().trim(); for (const kw of BLOCK_KEYWORDS) { if (name.includes(kw)) return 3; } if (name === "cup") return 3; for (const t3 of TIER_3_EXACT) { if (name === t3 || name.startsWith(t3)) return 3; } for (const t2 of TIER_2) { if (name.includes(t2)) return 2; } for (const t1 of TIER_1) { if (name.includes(t1)) return 1; } return 3; }
export function getTierMinProbability(tier) { if (tier === 1) return 0.62; if (tier === 2) return 0.68; return null; } export function isLeagueAllowed(tournamentName) { return getLeagueTier(tournamentName) < 3; }
